# Importing Necessary Libraries 

In [ ]:
import numpy as np
import pandas as pd
import os
import tensorflow as tf
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
df = pd.DataFrame()

directory = './AggregatedDataset/'
for filename in os.listdir(directory):
    if filename[0] == '.':
        continue
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f):
        temp = pd.read_csv(f)
        df = pd.concat([df, temp])

print(df)

            x0        y0        z0        x1        y1        z1        x2  \
0    -0.171263  0.056039  2.852897 -0.172357  0.328195  2.840483 -0.172608   
1    -0.170329  0.056418  2.852098 -0.171068  0.328502  2.838917 -0.170646   
2    -0.169850  0.056646  2.850483 -0.171149  0.328440  2.837448 -0.171608   
3    -0.170755  0.055544  2.848923 -0.172384  0.327309  2.837404 -0.173572   
4    -0.172305  0.054833  2.849287 -0.174495  0.326570  2.838649 -0.176505   
...        ...       ...       ...       ...       ...       ...       ...   
1597 -0.042952 -0.218804  2.629542 -0.038463  0.034474  2.627915 -0.028250   
1598 -0.117705  0.057641  2.839420 -0.087817  0.323763  2.808998 -0.058911   
1599 -0.143461  0.065574  2.839821 -0.111683  0.329658  2.813619 -0.081166   
1600 -0.173216  0.062522  2.820663 -0.151995  0.328140  2.804494 -0.131629   
1601 -0.152141  0.064745  2.841494 -0.138693  0.331558  2.816642 -0.123804   

            y2        z2        x3  ...       z23       x24    

In [ ]:
dataset_filename = 'final_dataset_volume_1.csv'
dataset = pd.read_csv(dataset_filename)
dataset

x0_0      y0_0      z0_0      x1_0      y1_0      z1_0      x2_0  \
0     -0.204509 -0.231852  2.754740 -0.183313  0.021745  2.722442 -0.160604   
1     -0.205910 -0.231284  2.753148 -0.183092  0.022023  2.721940 -0.157748   
2     -0.206187 -0.230854  2.752944 -0.181606  0.022386  2.722124 -0.154308   
3     -0.206352 -0.229995  2.752958 -0.179751  0.022750  2.722315 -0.150479   
4     -0.206131 -0.228837  2.753482 -0.178426  0.023735  2.722597 -0.148413   
...         ...       ...       ...       ...       ...       ...       ...   
32683  0.026913 -0.269149  1.986143  0.031897  0.014268  1.999952  0.037582   
32684 -0.151085 -0.242354  2.769809 -0.115528  0.040573  2.778128 -0.083593   
32685  0.222070 -0.014420  2.401597  0.234175  0.301999  2.372200  0.243291   
32686 -0.158039 -0.200949  2.864184 -0.121875  0.071257  2.867864 -0.083772   
32687 -0.175792 -0.252243  2.437925 -0.156868  0.025715  2.401402 -0.133253   

           y2_0      z2_0      x3_0  ...    x22_14    y22_14    z22_14  \
0      0.269536  2.678496 -0.150488  ... -0.294275 -0.228529  2.467200   
1      0.269648  2.678936 -0.148618  ... -0.322549 -0.229593  2.531100   
2      0.269743  2.679503 -0.146234  ... -0.312972 -0.244179  2.513334   
3      0.269884  2.679807 -0.144726  ... -0.291575 -0.203919  2.489133   
4      0.270744  2.680139 -0.143232  ... -0.211119 -0.166091  2.883111   
...         ...       ...       ...  ...       ...       ...       ...   
32683  0.289789  2.002094  0.039797  ... -0.120554 -0.344610  1.882555   
32684  0.316620  2.770875 -0.050294  ... -0.334549 -0.220945  2.428982   
32685  0.608476  2.332399  0.256374  ... -0.039968 -0.047680  2.286785   
32686  0.332362  2.861038 -0.055445  ... -0.108098 -0.266274  2.326225   
32687  0.296400  2.350872 -0.105743  ... -0.430705 -0.214115  2.139153   

         x23_14    y23_14    z23_14    x24_14    y24_14    z24_14  \
0      0.051053  0.284080  2.547323  0.084085  0.233071  2.580800   
1     -0.000089  0.298676  2.598341  0.024250  0.252613  2.579778   
2      0.077471  0.253935  2.508044  0.110522  0.192595  2.562273   
3      0.225467 -0.076853  2.423342  0.153054 -0.086606  2.446333   
4      0.124102 -0.292121  3.011770  0.076095 -0.245350  3.013428   
...         ...       ...       ...       ...       ...       ...   
32683  0.278531 -0.321069  1.853241  0.279595 -0.272307  1.849831   
32684  0.089193 -0.175894  2.429649  0.055558 -0.156731  2.479578   
32685  0.431304 -0.169775  2.311718  0.460617 -0.138403  2.286588   
32686  0.265670 -0.232723  1.927355  0.346758 -0.196454  1.977169   
32687 -0.198763 -0.222574  2.180512 -0.111141 -0.215188  2.155213   

       gestureLabel  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0  
...             ...  
32683           8.0  
32684           8.0  
32685           8.0  
32686           8.0  
32687           8.0  

[32688 rows x 1126 columns]

# Train Test Split

In [ ]:
features = dataset.iloc[:, :-1]
labels = dataset.iloc[:,-1]

categorical_labels = to_categorical(labels, num_classes = 9, dtype ="int32")
print(categorical_labels)
X_train, X_test, Y_train, Y_test = train_test_split(features, categorical_labels, test_size=0.2)
print(X_train)
print(Y_train)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]
           x0_0      y0_0      z0_0      x1_0      y1_0      z1_0      x2_0  \
18719 -0.149700 -0.154535  2.764081 -0.141267  0.080814  2.745136 -0.136264   
1632  -0.188968 -0.095530  2.061145 -0.183147  0.223128  2.050640 -0.175927   
31006 -0.036236 -0.003311  2.404890 -0.016882  0.222497  2.422970  0.002904   
16007  0.124403  0.066474  2.372620  0.150678  0.351241  2.337344  0.178346   
397   -0.086572 -0.247107  2.190364 -0.092994 -0.038029  2.269419 -0.097967   
...         ...       ...       ...       ...       ...       ...       ...   
13099  0.057932 -0.353345  2.127191  0.035851 -0.022027  2.145813  0.013843   
26345 -0.272203  0.035342  2.211323 -0.274508  0.326892  2.148127 -0.275745   
19805 -0.192723  0.063470  1.994513 -0.208797  0.308157  1.981156 -0.224567   
13540 -0.242890 -0.065410  2.143851 -0.250072  0.234147  2.107006 -0.254026   
5668  -0.23

# Constructing the Neural Network

In [ ]:
model = tf.keras.Sequential()
model.add(Dense(1024, name='hidden_1', activation='relu', input_shape=(1125,)))
model.add(Dense(1024, name='hidden_2', activation='relu'))
model.add(Dense(512, name='hidden_3', activation='relu'))
model.add(Dense(9, name='output', activation='softmax'))

NameError: name 'tf' is not defined

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_1 (Dense)            (None, 1024)              1153024   
                                                                 
 hidden_2 (Dense)            (None, 1024)              1049600   
                                                                 
 hidden_3 (Dense)            (None, 512)               524800    
                                                                 
 output (Dense)              (None, 9)                 4617      
                                                                 
Total params: 2,732,041
Trainable params: 2,732,041
Non-trainable params: 0
_________________________________________________________________


In [ ]:
optimizer = Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss=['categorical_crossentropy'], metrics=['accuracy'])

In [ ]:
callbacks = [
    EarlyStopping(patience=2, verbose=1), 
    ReduceLROnPlateau(factor=0.5, patience=10, verbose=1, min_lr=0.00001, cooldown=2, min_delta=0.001)
]

In [ ]:
model.fit(X_train, Y_train, epochs = 10, validation_split = 0.25, shuffle = True, callbacks = callbacks)

Epoch 1/10
613/613 [==============================] - 9s 15ms/step - loss: 0.1495 - accuracy: 0.9421 - val_loss: 0.1901 - val_accuracy: 0.9348 - lr: 1.0000e-04
Epoch 2/10
613/613 [==============================] - 9s 15ms/step - loss: 0.1425 - accuracy: 0.9456 - val_loss: 0.1131 - val_accuracy: 0.9550 - lr: 1.0000e-04
Epoch 3/10
613/613 [==============================] - 9s 15ms/step - loss: 0.1276 - accuracy: 0.9509 - val_loss: 0.1298 - val_accuracy: 0.9509 - lr: 1.0000e-04
Epoch 4/10
613/613 [==============================] - 9s 15ms/step - loss: 0.1239 - accuracy: 0.9527 - val_loss: 0.1333 - val_accuracy: 0.9512 - lr: 1.0000e-04
Epoch 4: early stopping


In [ ]:
y_pred = model.predict(X_test)
score = model.evaluate(X_test, Y_test, verbose=0)

205/205 [==============================] - 1s 2ms/step


In [ ]:
print(score[1])

0.921841561794281


In [ ]:
# print(accuracy_score(y_pred, Y_test))
print(y_pred[0])
y_pred = np.argmax(y_pred, axis=1)


[1.5703142e-09 1.0179595e-13 4.4833202e-04 4.2478144e-16 9.9955159e-01
 2.0163662e-12 4.6883460e-15 1.2679922e-10 1.8772041e-11]


# Hyperparameter Tuning

In [ ]:
def model_builder(hp):
    model = tf.keras.Sequential()
    # Tune the number of units in the first Dense layer
      # Choose an optimal value between 32-512
    hp_units_1 = hp.Int('units_1', min_value=512, max_value=1024, step=128)
    hp_units_2 = hp.Int('units_2', min_value=512, max_value=1024, step=128)
    hp_units_3 = hp.Int('units_3', min_value=512, max_value=1024, step=128)
    model.add(Dense(units=hp_units_1,name='hidden_1', activation='relu',input_shape=(1125,)))
    model.add(Dense(units=hp_units_2,name='hidden_2', activation='relu'))
    model.add(Dense(units=hp_units_3,name='hidden_3', activation='relu'))
    model.add(Dense(units=9,name='output', activation='softmax'))

  # Tune the learning rate for the optimizer
    hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])

    model.compile(optimizer = Adam(learning_rate=hp_learning_rate),
                loss=['categorical_crossentropy'],
                metrics=['accuracy'])

    return model

In [ ]:
import keras_tuner as kt
tuner = kt.Hyperband(model_builder,
                     objective='val_accuracy',
                     max_epochs=10,
                     factor=3,
                     directory='C:\\Notebook_File',
                     project_name='Tuning')

In [ ]:
stop_early = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)

In [ ]:
tuner.search(X_train, Y_train, epochs=50, validation_split=0.2, callbacks=[stop_early])

# Get the optimal hyperparameters
best_hps=tuner.get_best_hyperparameters(num_trials=1)[0]



Trial 30 Complete [00h 01m 20s]
val_accuracy: 0.9422562122344971

Best val_accuracy So Far: 0.9642447233200073
Total elapsed time: 00h 15m 09s
INFO:tensorflow:Oracle triggered exit


In [ ]:
print(f"""
The hyperparameter search is complete. The optimal numbers of units in the 3 densely-connected
layer are {best_hps.get('units_1'),best_hps.get('units_2'),best_hps.get('units_3')} and the optimal learning rate for the optimizer
is {best_hps.get('learning_rate')}.
""")


The hyperparameter search is complete. The optimal numbers of units in the 3 densely-connected
layer are (1024, 896, 896) and the optimal learning rate for the optimizer
is 0.0001.

